name: Security Scan

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r .
